"use client"

import './styles.css';
import { trpc } from './trpc';

export const metadata = {
  title: 'Welcome to web',
  description: 'Generated by create-nx-workspace',
};

function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}

export default trpc.withTRPC(RootLayout)