#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

valid_branch_regex="^Buildoo-[0-9]+-.*$"
# valid_branch_regex="main"

local_branch_name="$(git rev-parse --abbrev-ref HEAD)"

message="[pre-commit-hook] Your branch name is illegal. Please rename your branch with using following regex: $valid_branch_regex"

if [[ ! $local_branch_name =~ $valid_branch_regex ]]; then
    echo "$message"
    exit 1
fi

exit 0